export const ERROR_CODES = {
  // General
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Users / Candidates
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CANDIDATE_NOT_FOUND: "CANDIDATE_NOT_FOUND",

  // Jobs
  JOB_NOT_FOUND: "JOB_NOT_FOUND",

  // Database
  DB_ERROR: "DB_ERROR",
} as const;